image: python:3.8-buster ## MkDocs requies python.

pages:
  stage: deploy ## tell GitLab to deploy the website in this step.
  before_script: |
    apt-get update && apt-get install --yes jq curl wget
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  script: |
    mkdocs build -c -f mkdocs-en.yml
    mkdocs build -c -f mkdocs-fr.yml
    bash build-dev-docs.sh
    mkdocs build -c -f mkdocs-dev.yml
    mv site public
  artifacts:
    paths:
    - public
